//Even Fibonacci numbers
//* -------------------------- &&& -------------------------- *
/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.

 **/
function fibonacci() {

  var numero1 = 0;
  var numero2 = 1 ;
  var resultado_final = 0;

  for(var cont = 0; cont <= 100; cont++) {


    console.log('>>>>>>>>>>>>>>>>>> numero1', numero1);
    console.log('>>>>>>>>>>>>>>>>>> numero2', numero2);

    var resultado = numero1 + numero2
    console.log('resultadooooooooooooooooooooooooooooooooooo', resultado)
    console.log((resultado % 2 === 0 || resultado % 2 === 2));

    if(resultado % 2 === 0 || resultado % 2 === 2) {
      console.log('resultado primeira impressão ', resultado)
      console.log('resultado ....<<>>', resultado)
      resultado_final += resultado
    }

    if(4000000 < resultado_final) {
      console.log('resultado segunda impressão ', resultado)
      return resultado_final

    }

    numero1 = numero2
    numero2 = resultado
    console.log("######################### uma volta ##########################")
  }
  return resultado_final
}

console.log('>>>>>>>>>>>>>>>>', fibonacci())


//  3524578
